### ISSUE TITLE
Imports from Alembic are treated as first-party

### ISSUE THREAD

**Issue by dirn** [PyGotham/awards#17]
[seed-isort-config](https://pypi.org/p/seed-isort-config) is used to keep [isort](https://pypi.org/p/isort)'s list of known third-party imports up-to-date. For some reason, though, it fails to identify [Alembic](https://alembic.sqlalchemy.org) as being a third-party library and sorts it with the first-party imports. This should be fixed.

**Comment by jonafato** [comment]
This seems to be because the migrations directory is named `alembic`. I'm guessing that `seed-isort-config` is seeing this and thinking that it's a local package rather than a collection of scripts. `seed-isort-config` has some configuration options that may help here, but renaming the directory to `migrations` or something similar is probably the easiest fix.

**Comment by dirn** [comment]
That makes a lot of sense. Good thinking!
